- name: System Preparation | /etc/security/limits.conf
  pam_limits:
    domain: "{{item.domain}}"
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items:
    - {domain: "*", limit_type: soft, limit_item: nofile, value: 64000 }
    - {domain: "*", limit_type: soft, limit_item: nproc,  value: 64000 }
    - {domain: "*", limit_type: hard, limit_item: nofile, value: 64000 }
    - {domain: "*", limit_type: hard, limit_item: nproc,  value: 64000 }
  tags: limits
