---
- name: CDH5 | Add repository
  copy:
    src: files/cloudera-manager.repo
    dest: /etc/yum.repos.d/cloudera-manager.repo

- name: CDH5 | Install Cloudera Manager
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - cloudera-manager-daemons 
    - cloudera-manager-server
