---
- name: Common tasks for all hosts
  hosts: all
  remote_user: root
#  become: true 

  roles:
    - roles/limits
    - roles/sysctl
    - roles/hugepages
    - roles/tuned
    - roles/selinux
    - roles/nscd
    - roles/firewalld
